<?php
// Language translations for Smart Chashi
// Usage: __('key') or get_text('key')

$languages = [
    'en' => [
        // Common
        'title' => 'Smart Chashi',
        'dashboard' => 'Dashboard',
        'crops' => 'Crops',
        'disease_detection' => 'Disease Detection',
        'chat' => 'Chat',
        'weather' => 'Weather',
        'marketplace' => 'Marketplace',
        'community' => 'Community',
        'profile' => 'Profile',
        'logout' => 'Logout',
        'home' => 'Home',
        'login' => 'Login',
        'register' => 'Register',

        // Profile Page
        'your_profile' => 'Your Profile',
        'manage_account' => 'Manage your account and farming information',
        'personal_information' => 'Personal Information',
        'first_name' => 'First Name',
        'last_name' => 'Last Name',
        'email' => 'Email',
        'phone' => 'Phone',
        'account_type' => 'Account Type',
        'update_profile' => 'Update Profile',
        'farming_profile' => 'Farming Profile',
        'land_size' => 'Land Size (hectares)',
        'experience_level' => 'Experience Level',
        'beginner' => 'Beginner (0-2 years)',
        'intermediate' => 'Intermediate (2-5 years)',
        'advanced' => 'Advanced (5+ years)',
        'primary_crop' => 'Primary Crop',
        'region_district' => 'Region/District',
        'select' => 'Select...',
        'update_farming_info' => 'Update Farming Info',
        'security' => 'Security',
        'current_password' => 'Current Password',
        'new_password' => 'New Password',
        'confirm_password' => 'Confirm Password',
        'change_password' => 'Change Password',
        'account_statistics' => 'Account Statistics',
        'account_created' => 'Account Created',
        'last_login' => 'Last Login',
        'total_crops' => 'Total Crops Tracked',
        'chat_messages' => 'Chat Messages',
        'community_posts' => 'Community Posts',
        'preferences' => 'Preferences',
        'preferred_language' => 'Preferred Language',
        'theme' => 'Theme',
        'light' => 'Light',
        'dark' => 'Dark',
        'marketing_emails' => 'Marketing emails (new features, tips)',
        'product_updates' => 'Product updates and news',
        'save_preferences' => 'Save Preferences',
        'danger_zone' => 'Danger Zone',
        'delete_account' => 'Delete Account',
        'delete_account_warning' => 'Delete your account and all associated data. This action cannot be undone.',
        'english' => 'English',
        'bengali' => 'বাংলা',
        'language' => 'Language',
        'profile_photo' => 'Profile Photo',
        'change_photo' => 'Change Photo',
        
        // Home Page
        'smart_chashi' => 'Smart Chashi',
        'ai_farming_assistant' => 'AI Farming Assistant',
        'get_smart_farming' => 'Get smart farming advice & real-time weather alerts',
        'track_manage_crops' => 'Track & manage your crops',
        'manage' => 'Manage',
        'disease_check' => 'Disease Check',
        'detect_crop_diseases' => 'Detect crop diseases with AI',
        'check' => 'Check',
        'ask_farming_questions' => 'Ask farming questions',
        'realtime_weather' => 'Real-time weather & alerts',
        'view' => 'View',
        'buy_sell_products' => 'Buy & sell farm products',
        'browse' => 'Browse',
        'connect_farmers' => 'Connect with farmers',
        'join' => 'Join',
        'why_choose_smart_chashi' => 'Why Choose Smart Chashi?',
        'mobile_first_design' => 'Mobile-First Design',
        'mobile_first_desc' => 'Optimized for smartphones. Works perfectly on all devices with zero lag.',
        'secure_private' => 'Secure & Private',
        'secure_private_desc' => 'Your data is encrypted and secure. We respect your privacy completely.',
        'works_offline' => 'Works Offline',
        'works_offline_desc' => 'Access basic features even without internet connection. Syncs when you are back online.',
        'free_open' => 'Free & Open',
        'free_open_desc' => 'Basic features are free for all farmers. Premium options available for advanced features.',
        'bangla_support' => 'Bangla Support',
        'bangla_support_desc' => 'Available in both Bangla and English. AI chat supports your native language.',
        'always_updated' => 'Always Updated',
        'always_updated_desc' => 'New features added regularly. You always get the latest technology without waiting.',
        
        // Dashboard
        'hi' => 'Hi',
        'welcome_dashboard' => 'Welcome to your farm dashboard',
        'alerts' => 'Alerts',
        'health' => 'Health',
        'location' => 'Location',
        'quick_links' => 'Quick Links',
        'your_crops' => 'Your Crops',
        'no_crops_yet' => 'No Crops Yet',
        'add_first_crop' => 'Add your first crop',
        
        // Crops Page
        'my_crops' => 'My Crops',
        'add_crop' => 'Add Crop',
        'crop_name' => 'Crop Name',
        'variety' => 'Variety',
        'area_hectares' => 'Area (hectares)',
        'planted_date' => 'Planted Date',
        'expected_harvest' => 'Expected Harvest',
        'status' => 'Status',
        'variety_eg' => 'e.g., BRRI dhan 28',
        'rice_wheat_etc' => 'Rice, Wheat, etc',
        'no_crops_added' => 'No Crops Added Yet',
        'add_first_crop_form' => 'Add your first crop using the form on the left to get started.',
        'delete' => 'Delete',
        'planted' => 'Planted',
        
        // Disease Detection
        'analyze_photo' => 'Analyze Photo',
        'select_crop' => 'Select Crop',
        'choose_crop' => 'Choose crop',
        'upload_image' => 'Upload Image',
        'jpg_png_max' => 'JPG, PNG (Max 50MB)',
        'analyze' => 'Analyze',
        'how_to_use' => 'How to Use',
        'take_clear_photo' => 'Take a clear photo of affected area',
        'good_lighting' => 'Good lighting helps accuracy',
        'upload_get_results' => 'Upload and get results',
        'add_crop_first' => 'Add a crop first to analyze diseases',
        
        // Chat Page
        'chat_with_chashi' => 'Chat with Chashi',
        'ask_questions' => 'Ask Questions',
        'no_chat_history' => 'No chat history yet. Start asking!',
        'ask_about_crops' => 'Ask about crops, diseases, weather...',
        'send' => 'Send',
        'ask_about' => 'Ask About',
        'crop_management_tips' => 'Crop management & tips',
        'disease_identification' => 'Disease identification',
        'fertilizer_watering' => 'Fertilizer & watering',
        'weather_alerts' => 'Weather & alerts',
        'farm_equipment' => 'Farm equipment',
        
        // Weather Page
        'weather_alerts_title' => 'Weather & Alerts',
        'realtime_weather_info' => 'Real-time weather information and disaster alerts',
        'current_weather' => 'Current Weather',
        'humidity' => 'Humidity',
        'wind_speed' => 'Wind Speed',
        'rainfall' => 'Rainfall',
        'pressure' => 'Pressure',
        'your_region' => 'Your Region',
        'auto_detect_location' => 'Auto-Detect Location',
        'day_forecast' => '7-Day Forecast',
        'day' => 'Day',
        'condition' => 'Condition',
        'max_temp' => 'Max Temp',
        'min_temp' => 'Min Temp',
        'today' => 'Today',
        'tomorrow' => 'Tomorrow',
        
        // Marketplace
        'farm_marketplace' => 'Farm Marketplace',
        'buy_sell_direct' => 'Buy and sell farm products directly from farmers',
        'add_your_product' => 'Add Your Product',
        'product_name' => 'Product Name',
        'description' => 'Description',
        'price_per_unit' => 'Price per Unit (৳)',
        'quantity_available' => 'Quantity Available',
        'list_product' => 'List Product',
        'search_filter' => 'Search & Filter',
        'search_products' => 'Search products...',
        'filter_category' => 'Filter by Category',
        'filter_region' => 'Filter by Region',
        'all_categories' => 'All Categories',
        'all_regions' => 'All Regions',
        'available_products' => 'Available Products',
        'available' => 'Available',
        'contact_seller' => 'Contact Seller',
        
        // Community
        'farmer_community' => 'Farmer Community Forum',
        'share_experiences' => 'Share experiences, ask questions, and learn from other farmers',
        'create_new_post' => 'Create New Post',
        'title' => 'Title',
        'whats_on_mind' => 'What\'s on your mind?',
        'category' => 'Category',
        'content' => 'Content',
        'share_experience' => 'Share your experience or question...',
        'post' => 'Post',
        'community_stats' => 'Community Stats',
        'total_farmers' => 'Total Farmers',
        'posts_today' => 'Posts Today',
        'active_discussions' => 'Active Discussions',
        'popular_topics' => 'Popular Topics',
        'recent_posts' => 'Recent Posts',
        'likes' => 'Likes',
        'reply' => 'Reply',
        
        // Login Page
        'login_to_smart_chashi' => 'Login to Smart Chashi',
        'access_dashboard' => 'Access your farming dashboard and manage your crops',
        'email_address' => 'Email Address',
        'password' => 'Password',
        'no_account' => 'Don\'t have an account?',
        'register_here' => 'Register here',
        'new_to_smart_chashi' => 'New to Smart Chashi?',
        'join_thousands' => 'Join thousands of farmers using AI-powered smart farming.',
        'key_features' => 'Key Features',
        'create_account' => 'Create Account',
        
        // Register Page
        'join_smart_chashi' => 'Join Smart Chashi',
        'create_farming_journey' => 'Create your account and start your smart farming journey',
        'already_account' => 'Already have an account?',
        'login_here' => 'Login here',
        'farmer' => 'Farmer',
        'agriculture_officer' => 'Agriculture Officer',
        'agree_terms' => 'I agree to the Terms of Service and Privacy Policy',
        'minimum_8_chars' => 'Minimum 8 characters',
        'reenter_password' => 'Re-enter password',
        
        // AI Agent Page
        'agent_page_title' => 'Smart Chashi - Your Expert Agricultural AI Assistant',
        'agent_tagline' => 'Ask your agricultural questions and get accurate AI-powered answers!',
        'agent_placeholder' => 'Enter your agricultural question here...',
        'voice_button' => 'Ask with Voice',
        'alert_title_voice_na' => 'Voice Not Available',
        'voice_text_reading' => 'Reading answer...',
        'detected_language' => 'Detected Language',
        'translated_query' => 'Translated Query',
        'error_connection' => 'Error: Could not connect to server. Please check your internet connection.',
        'stop_voice' => 'Stop Voice',
    ],
    'bn' => [
        // Common
        'title' => 'স্মার্ট চাষি',
        'dashboard' => 'ড্যাশবোর্ড',
        'crops' => 'ফসলসমূহ',
        'disease_detection' => 'রোগ নির্ণয়',
        'chat' => 'চ্যাট',
        'weather' => 'আবহাওয়া',
        'marketplace' => 'বাজার',
        'community' => 'কমিউনিটি',
        'profile' => 'প্রোফাইল',
        'logout' => 'লগ আউট',
        'home' => 'হোম',
        'login' => 'লগইন',
        'register' => 'নিবন্ধন',

        // Profile Page
        'your_profile' => 'আপনার প্রোফাইল',
        'manage_account' => 'আপনার অ্যাকাউন্ট ও কৃষি সংক্রান্ত তথ্য পরিচালনা করুন',
        'personal_information' => 'ব্যক্তিগত তথ্য',
        'first_name' => 'নামের প্রথম অংশ',
        'last_name' => 'নামের শেষ অংশ',
        'email' => 'ইমেইল',
        'phone' => 'ফোন নম্বর',
        'account_type' => 'অ্যাকাউন্টের ধরন',
        'update_profile' => 'প্রোফাইল হালনাগাদ করুন',
        'farming_profile' => 'কৃষি প্রোফাইল',
        'land_size' => 'জমির পরিমাণ (হেক্টর)',
        'experience_level' => 'অভিজ্ঞতার স্তর',
        'beginner' => 'নবীন (০–২ বছর)',
        'intermediate' => 'মধ্যম (২–৫ বছর)',
        'advanced' => 'অভিজ্ঞ (৫+ বছর)',
        'primary_crop' => 'প্রধান ফসল',
        'region_district' => 'অঞ্চল / জেলা',
        'select' => 'নির্বাচন করুন',
        'update_farming_info' => 'কৃষি তথ্য হালনাগাদ করুন',
        'security' => 'নিরাপত্তা',
        'current_password' => 'বর্তমান পাসওয়ার্ড',
        'new_password' => 'নতুন পাসওয়ার্ড',
        'confirm_password' => 'পাসওয়ার্ড নিশ্চিত করুন',
        'change_password' => 'পাসওয়ার্ড পরিবর্তন',
        'account_statistics' => 'অ্যাকাউন্ট পরিসংখ্যান',
        'account_created' => 'অ্যাকাউন্ট তৈরির তারিখ',
        'last_login' => 'সর্বশেষ লগইন',
        'total_crops' => 'মোট ফসল সংখ্যা',
        'chat_messages' => 'চ্যাট বার্তা',
        'community_posts' => 'কমিউনিটি পোস্ট',
        'preferences' => 'পছন্দসমূহ',
        'preferred_language' => 'পছন্দের ভাষা',
        'theme' => 'থিম',
        'light' => 'হালকা',
        'dark' => 'গাঢ়',
        'marketing_emails' => 'বিপণন ইমেইল (নতুন ফিচার ও টিপস)',
        'product_updates' => 'পণ্য সংক্রান্ত আপডেট ও সংবাদ',
        'save_preferences' => 'পছন্দ সংরক্ষণ করুন',
        'danger_zone' => 'ঝুঁকিপূর্ণ এলাকা',
        'delete_account' => 'অ্যাকাউন্ট মুছে ফেলুন',
        'delete_account_warning' => 'এই কাজটি করলে আপনার অ্যাকাউন্ট ও সংশ্লিষ্ট সকল তথ্য স্থায়ীভাবে মুছে যাবে। এটি আর ফেরত আনা যাবে না।',
        'english' => 'ইংরেজি',
        'bengali' => 'বাংলা',
        'language' => 'ভাষা',
        'profile_photo' => 'প্রোফাইল ছবি',
        'change_photo' => 'ছবি পরিবর্তন করুন',

        // Home Page
        'smart_chashi' => 'স্মার্ট চাষি',
        'ai_farming_assistant' => 'এআই-ভিত্তিক কৃষি সহায়ক',
        'get_smart_farming' => 'স্মার্ট কৃষি পরামর্শ ও রিয়েল-টাইম আবহাওয়া সতর্কতা পান',
        'track_manage_crops' => 'আপনার ফসল সহজে ট্র্যাক ও পরিচালনা করুন',
        'manage' => 'পরিচালনা',
        'disease_check' => 'রোগ পরীক্ষা',
        'detect_crop_diseases' => 'এআই ব্যবহার করে ফসলের রোগ শনাক্ত করুন',
        'check' => 'পরীক্ষা করুন',
        'ask_farming_questions' => 'কৃষি বিষয়ক প্রশ্ন করুন',
        'realtime_weather' => 'রিয়েল-টাইম আবহাওয়া ও সতর্কতা',
        'view' => 'দেখুন',
        'buy_sell_products' => 'খামার পণ্য ক্রয় ও বিক্রয় করুন',
        'browse' => 'ব্রাউজ করুন',
        'connect_farmers' => 'অন্যান্য কৃষকের সাথে সংযুক্ত হন',
        'join' => 'যোগ দিন',
        'why_choose_smart_chashi' => 'কেন স্মার্ট চাষি ব্যবহার করবেন?',
        'mobile_first_design' => 'মোবাইল-ফার্স্ট ডিজাইন',
        'mobile_first_desc' => 'স্মার্টফোনের জন্য বিশেষভাবে অপ্টিমাইজ করা, সব ডিভাইসে সমানভাবে কার্যকর।',
        'secure_private' => 'নিরাপদ ও গোপনীয়',
        'secure_private_desc' => 'আপনার তথ্য সম্পূর্ণভাবে এনক্রিপ্টেড ও সুরক্ষিত রাখা হয়।',
        'works_offline' => 'অফলাইন ব্যবহারের সুবিধা',
        'works_offline_desc' => 'ইন্টারনেট ছাড়াই মৌলিক ফিচার ব্যবহার করুন, অনলাইনে এলে স্বয়ংক্রিয় সিঙ্ক হবে।',
        'free_open' => 'বিনামূল্যে ও উন্মুক্ত',
        'free_open_desc' => 'সকল কৃষকের জন্য মৌলিক সুবিধা বিনামূল্যে প্রদান করা হয়।',
        'bangla_support' => 'বাংলা ভাষা সমর্থন',
        'bangla_support_desc' => 'বাংলা ও ইংরেজি উভয় ভাষায় সম্পূর্ণ সহায়তা।',
        'always_updated' => 'নিয়মিত হালনাগাদ',
        'always_updated_desc' => 'নতুন ফিচার ও প্রযুক্তি নিয়মিত যুক্ত করা হয়।',
    ]

];

// Get current language
function get_language() {
    if (isset($_SESSION['language'])) {
        return $_SESSION['language'];
    }
    if (isset($_COOKIE['language'])) {
        return $_COOKIE['language'];
    }
    return 'en'; // Default language
}

// Translate text
function __($key) {
    global $languages;
    $lang = get_language();
    
    if (isset($languages[$lang][$key])) {
        return $languages[$lang][$key];
    }
    return $languages['en'][$key] ?? $key;
}

// Alias for __()
function get_text($key) {
    return __($key);
}
