<?php
// Language translations for Smart Chashi
// Usage: __('key') or get_text('key')

$languages = [
    'en' => [
        // Common
        'title' => 'Smart Chashi',
        'dashboard' => 'Dashboard',
        'crops' => 'Crops',
        'disease_detection' => 'Disease Detection',
        'chat' => 'Chat',
        'weather' => 'Weather',
        'marketplace' => 'Marketplace',
        'community' => 'Community',
        'profile' => 'Profile',
        'logout' => 'Logout',
        'home' => 'Home',
        'login' => 'Login',
        'register' => 'Register',

        // Profile Page
        'your_profile' => 'Your Profile',
        'manage_account' => 'Manage your account and farming information',
        'personal_information' => 'Personal Information',
        'first_name' => 'First Name',
        'last_name' => 'Last Name',
        'email' => 'Email',
        'phone' => 'Phone',
        'account_type' => 'Account Type',
        'update_profile' => 'Update Profile',
        'farming_profile' => 'Farming Profile',
        'land_size' => 'Land Size (hectares)',
        'experience_level' => 'Experience Level',
        'beginner' => 'Beginner (0-2 years)',
        'intermediate' => 'Intermediate (2-5 years)',
        'advanced' => 'Advanced (5+ years)',
        'primary_crop' => 'Primary Crop',
        'region_district' => 'Region/District',
        'select' => 'Select...',
        'update_farming_info' => 'Update Farming Info',
        'security' => 'Security',
        'current_password' => 'Current Password',
        'new_password' => 'New Password',
        'confirm_password' => 'Confirm Password',
        'change_password' => 'Change Password',
        'account_statistics' => 'Account Statistics',
        'account_created' => 'Account Created',
        'last_login' => 'Last Login',
        'total_crops' => 'Total Crops Tracked',
        'chat_messages' => 'Chat Messages',
        'community_posts' => 'Community Posts',
        'preferences' => 'Preferences',
        'preferred_language' => 'Preferred Language',
        'theme' => 'Theme',
        'light' => 'Light',
        'dark' => 'Dark',
        'marketing_emails' => 'Marketing emails (new features, tips)',
        'product_updates' => 'Product updates and news',
        'save_preferences' => 'Save Preferences',
        'danger_zone' => 'Danger Zone',
        'delete_account' => 'Delete Account',
        'delete_account_warning' => 'Delete your account and all associated data. This action cannot be undone.',
        'english' => 'English',
        'bengali' => 'বাংলা',
        'language' => 'Language',
        
        // Home Page
        'smart_chashi' => 'Smart Chashi',
        'ai_farming_assistant' => 'AI Farming Assistant',
        'get_smart_farming' => 'Get smart farming advice & real-time weather alerts',
        'track_manage_crops' => 'Track & manage your crops',
        'manage' => 'Manage',
        'disease_check' => 'Disease Check',
        'detect_crop_diseases' => 'Detect crop diseases with AI',
        'check' => 'Check',
        'ask_farming_questions' => 'Ask farming questions',
        'realtime_weather' => 'Real-time weather & alerts',
        'view' => 'View',
        'buy_sell_products' => 'Buy & sell farm products',
        'browse' => 'Browse',
        'connect_farmers' => 'Connect with farmers',
        'join' => 'Join',
        'why_choose_smart_chashi' => 'Why Choose Smart Chashi?',
        'mobile_first_design' => 'Mobile-First Design',
        'mobile_first_desc' => 'Optimized for smartphones. Works perfectly on all devices with zero lag.',
        'secure_private' => 'Secure & Private',
        'secure_private_desc' => 'Your data is encrypted and secure. We respect your privacy completely.',
        'works_offline' => 'Works Offline',
        'works_offline_desc' => 'Access basic features even without internet connection. Syncs when you are back online.',
        'free_open' => 'Free & Open',
        'free_open_desc' => 'Basic features are free for all farmers. Premium options available for advanced features.',
        'bangla_support' => 'Bangla Support',
        'bangla_support_desc' => 'Available in both Bangla and English. AI chat supports your native language.',
        'always_updated' => 'Always Updated',
        'always_updated_desc' => 'New features added regularly. You always get the latest technology without waiting.',
        
        // Dashboard
        'hi' => 'Hi',
        'welcome_dashboard' => 'Welcome to your farm dashboard',
        'alerts' => 'Alerts',
        'health' => 'Health',
        'location' => 'Location',
        'quick_links' => 'Quick Links',
        'your_crops' => 'Your Crops',
        'no_crops_yet' => 'No Crops Yet',
        'add_first_crop' => 'Add your first crop',
        
        // Crops Page
        'my_crops' => 'My Crops',
        'add_crop' => 'Add Crop',
        'crop_name' => 'Crop Name',
        'variety' => 'Variety',
        'area_hectares' => 'Area (hectares)',
        'planted_date' => 'Planted Date',
        'expected_harvest' => 'Expected Harvest',
        'status' => 'Status',
        'variety_eg' => 'e.g., BRRI dhan 28',
        'rice_wheat_etc' => 'Rice, Wheat, etc',
        'no_crops_added' => 'No Crops Added Yet',
        'add_first_crop_form' => 'Add your first crop using the form on the left to get started.',
        'delete' => 'Delete',
        'planted' => 'Planted',
        
        // Disease Detection
        'analyze_photo' => 'Analyze Photo',
        'select_crop' => 'Select Crop',
        'choose_crop' => 'Choose crop',
        'upload_image' => 'Upload Image',
        'jpg_png_max' => 'JPG, PNG (Max 50MB)',
        'analyze' => 'Analyze',
        'how_to_use' => 'How to Use',
        'take_clear_photo' => 'Take a clear photo of affected area',
        'good_lighting' => 'Good lighting helps accuracy',
        'upload_get_results' => 'Upload and get results',
        'add_crop_first' => 'Add a crop first to analyze diseases',
        
        // Chat Page
        'chat_with_chashi' => 'Chat with Chashi',
        'ask_questions' => 'Ask Questions',
        'no_chat_history' => 'No chat history yet. Start asking!',
        'ask_about_crops' => 'Ask about crops, diseases, weather...',
        'send' => 'Send',
        'ask_about' => 'Ask About',
        'crop_management_tips' => 'Crop management & tips',
        'disease_identification' => 'Disease identification',
        'fertilizer_watering' => 'Fertilizer & watering',
        'weather_alerts' => 'Weather & alerts',
        'farm_equipment' => 'Farm equipment',
        
        // Weather Page
        'weather_alerts_title' => 'Weather & Alerts',
        'realtime_weather_info' => 'Real-time weather information and disaster alerts',
        'current_weather' => 'Current Weather',
        'humidity' => 'Humidity',
        'wind_speed' => 'Wind Speed',
        'rainfall' => 'Rainfall',
        'pressure' => 'Pressure',
        'your_region' => 'Your Region',
        'auto_detect_location' => 'Auto-Detect Location',
        'day_forecast' => '7-Day Forecast',
        'day' => 'Day',
        'condition' => 'Condition',
        'max_temp' => 'Max Temp',
        'min_temp' => 'Min Temp',
        'today' => 'Today',
        'tomorrow' => 'Tomorrow',
        
        // Marketplace
        'farm_marketplace' => 'Farm Marketplace',
        'buy_sell_direct' => 'Buy and sell farm products directly from farmers',
        'add_your_product' => 'Add Your Product',
        'product_name' => 'Product Name',
        'description' => 'Description',
        'price_per_unit' => 'Price per Unit (৳)',
        'quantity_available' => 'Quantity Available',
        'list_product' => 'List Product',
        'search_filter' => 'Search & Filter',
        'search_products' => 'Search products...',
        'filter_category' => 'Filter by Category',
        'filter_region' => 'Filter by Region',
        'all_categories' => 'All Categories',
        'all_regions' => 'All Regions',
        'available_products' => 'Available Products',
        'available' => 'Available',
        'contact_seller' => 'Contact Seller',
        
        // Community
        'farmer_community' => 'Farmer Community Forum',
        'share_experiences' => 'Share experiences, ask questions, and learn from other farmers',
        'create_new_post' => 'Create New Post',
        'title' => 'Title',
        'whats_on_mind' => 'What\'s on your mind?',
        'category' => 'Category',
        'content' => 'Content',
        'share_experience' => 'Share your experience or question...',
        'post' => 'Post',
        'community_stats' => 'Community Stats',
        'total_farmers' => 'Total Farmers',
        'posts_today' => 'Posts Today',
        'active_discussions' => 'Active Discussions',
        'popular_topics' => 'Popular Topics',
        'recent_posts' => 'Recent Posts',
        'likes' => 'Likes',
        'reply' => 'Reply',
        
        // Login Page
        'login_to_smart_chashi' => 'Login to Smart Chashi',
        'access_dashboard' => 'Access your farming dashboard and manage your crops',
        'email_address' => 'Email Address',
        'password' => 'Password',
        'no_account' => 'Don\'t have an account?',
        'register_here' => 'Register here',
        'new_to_smart_chashi' => 'New to Smart Chashi?',
        'join_thousands' => 'Join thousands of farmers using AI-powered smart farming.',
        'key_features' => 'Key Features',
        'create_account' => 'Create Account',
        
        // Register Page
        'join_smart_chashi' => 'Join Smart Chashi',
        'create_farming_journey' => 'Create your account and start your smart farming journey',
        'already_account' => 'Already have an account?',
        'login_here' => 'Login here',
        'farmer' => 'Farmer',
        'agriculture_officer' => 'Agriculture Officer',
        'agree_terms' => 'I agree to the Terms of Service and Privacy Policy',
        'minimum_8_chars' => 'Minimum 8 characters',
        'reenter_password' => 'Re-enter password',
        
        // AI Agent Page
        'agent_page_title' => 'Smart Chashi - Your Expert Agricultural AI Assistant',
        'agent_tagline' => 'Ask your agricultural questions and get accurate AI-powered answers!',
        'agent_placeholder' => 'Enter your agricultural question here...',
        'voice_button' => 'Ask with Voice',
        'alert_title_voice_na' => 'Voice Not Available',
        'voice_text_reading' => 'Reading answer...',
        'detected_language' => 'Detected Language',
        'translated_query' => 'Translated Query',
        'error_connection' => 'Error: Could not connect to server. Please check your internet connection.',
        'stop_voice' => 'Stop Voice',
    ],
    'bn' => [
        // Common
        'title' => 'স্মার্ট চাষি',
        'dashboard' => 'ড্যাশবোর্ড',
        'crops' => 'ফসল',
        'disease_detection' => 'রোগ সনাক্তকরণ',
        'chat' => 'চ্যাট',
        'weather' => 'আবহাওয়া',
        'marketplace' => 'বাজার',
        'community' => 'সম্প্রদায়',
        'profile' => 'প্রোফাইল',
        'logout' => 'লগআউট',
        'home' => 'হোম',
        'login' => 'লগইন',
        'register' => 'রেজিস্টার',

        // Profile Page
        'your_profile' => 'আপনার প্রোফাইল',
        'manage_account' => 'আপনার অ্যাকাউন্ট এবং চাষাবাদ তথ্য পরিচালনা করুন',
        'personal_information' => 'ব্যক্তিগত তথ্য',
        'first_name' => 'প্রথম নাম',
        'last_name' => 'শেষ নাম',
        'email' => 'ইমেইল',
        'phone' => 'ফোন',
        'account_type' => 'অ্যাকাউন্ট প্রকার',
        'update_profile' => 'প্রোফাইল আপডেট করুন',
        'farming_profile' => 'চাষাবাদ প্রোফাইল',
        'land_size' => 'জমির আকার (হেক্টর)',
        'experience_level' => 'অভিজ্ঞতার স্তর',
        'beginner' => 'শিক্ষানবিস (০-২ বছর)',
        'intermediate' => 'মধ্যম (২-৫ বছর)',
        'advanced' => 'উন্নত (৫+ বছর)',
        'primary_crop' => 'প্রধান ফসল',
        'region_district' => 'অঞ্চল/জেলা',
        'select' => 'নির্বাচন করুন...',
        'update_farming_info' => 'চাষাবাদ তথ্য আপডেট করুন',
        'security' => 'নিরাপত্তা',
        'current_password' => 'বর্তমান পাসওয়ার্ড',
        'new_password' => 'নতুন পাসওয়ার্ড',
        'confirm_password' => 'পাসওয়ার্ড নিশ্চিত করুন',
        'change_password' => 'পাসওয়ার্ড পরিবর্তন করুন',
        'account_statistics' => 'অ্যাকাউন্ট পরিসংখ্যান',
        'account_created' => 'অ্যাকাউন্ট তৈরি',
        'last_login' => 'শেষ লগইন',
        'total_crops' => 'মোট ফসল',
        'chat_messages' => 'চ্যাট বার্তা',
        'community_posts' => 'সম্প্রদায়ের পোস্ট',
        'preferences' => 'পছন্দ',
        'preferred_language' => 'পছন্দের ভাষা',
        'theme' => 'থিম',
        'light' => 'হালকা',
        'dark' => 'অন্ধকার',
        'marketing_emails' => 'বিপণন ইমেইল (নতুন বৈশিষ্ট্য, টিপস)',
        'product_updates' => 'পণ্য আপডেট এবং সংবাদ',
        'save_preferences' => 'পছন্দ সংরক্ষণ করুন',
        'danger_zone' => 'বিপদ অঞ্চল',
        'delete_account' => 'অ্যাকাউন্ট মুছুন',
        'delete_account_warning' => 'আপনার অ্যাকাউন্ট এবং সমস্ত সম্পর্কিত ডেটা মুছুন। এই পদক্ষেপ পূর্বাবাস করা যায় না।',
        'english' => 'English',
        'bengali' => 'বাংলা',
        'language' => 'ভাষা',
        
        // Home Page
        'smart_chashi' => 'স্মার্ট চাষি',
        'ai_farming_assistant' => 'এআই কৃষি সহায়ক',
        'get_smart_farming' => 'স্মার্ট কৃষি পরামর্শ এবং রিয়েল-টাইম আবহাওয়া সতর্কতা পান',
        'track_manage_crops' => 'আপনার ফসল ট্র্যাক এবং পরিচালনা করুন',
        'manage' => 'পরিচালনা করুন',
        'disease_check' => 'রোগ পরীক্ষা',
        'detect_crop_diseases' => 'এআই দিয়ে ফসলের রোগ সনাক্ত করুন',
        'check' => 'পরীক্ষা করুন',
        'ask_farming_questions' => 'কৃষি প্রশ্ন জিজ্ঞাসা করুন',
        'realtime_weather' => 'রিয়েল-টাইম আবহাওয়া এবং সতর্কতা',
        'view' => 'দেখুন',
        'buy_sell_products' => 'খামার পণ্য ক্রয় এবং বিক্রয় করুন',
        'browse' => 'ব্রাউজ করুন',
        'connect_farmers' => 'কৃষকদের সাথে সংযুক্ত হন',
        'join' => 'যোগ দিন',
        'why_choose_smart_chashi' => 'কেন স্মার্ট চাষি নির্বাচন করবেন?',
        'mobile_first_design' => 'মোবাইল-প্রথম ডিজাইন',
        'mobile_first_desc' => 'স্মার্টফোনের জন্য অপ্টিমাইজ করা। সব ডিভাইসে নিখুঁতভাবে কাজ করে।',
        'secure_private' => 'নিরাপদ এবং গোপনীয়',
        'secure_private_desc' => 'আপনার তথ্য সম্পূর্ণ এনক্রিপ্টেড এবং সুরক্ষিত। আমরা আপনার গোপনীয়তাকে সম্মান করি।',
        'works_offline' => 'ইন্টারনেট ছাড়াই চলে',
        'works_offline_desc' => 'ইন্টারনেট সংযোগ ছাড়াই মৌলিক সুবিধা ব্যবহার করুন। অনলাইনে এলে স্বয়ংক্রিয়ভাবে সিঙ্ক হয়।',
        'free_open' => 'বিনামূল্যে এবং উন্মুক্ত',
        'free_open_desc' => 'সকল কৃষকের জন্য মূল সুবিধা বিনামূল্যে। উন্নত ফিচারের জন্য প্রিমিয়াম অপশন আছে।',
        'bangla_support' => 'বাংলা ভাষা সমর্থন',
        'bangla_support_desc' => 'বাংলা এবং ইংরেজি উভয় ভাষায় উপলব্ধ। এআই চ্যাট আপনার মাতৃভাষায় সাহায্য করে।',
        'always_updated' => 'সবসময় আপডেট',
        'always_updated_desc' => 'নিয়মিত নতুন ফিচার যোগ হয়। অপেক্ষা না করেই সর্বশেষ প্রযুক্তি পান।',
        
        // Dashboard
        'hi' => 'হাই',
        'welcome_dashboard' => 'আপনার খামার ড্যাশবোর্ডে স্বাগতম',
        'alerts' => 'সতর্কতা',
        'health' => 'স্বাস্থ্য',
        'location' => 'অবস্থান',
        'quick_links' => 'দ্রুত লিঙ্ক',
        'your_crops' => 'আপনার ফসল',
        'no_crops_yet' => 'এখনও কোন ফসল নেই',
        'add_first_crop' => 'আপনার প্রথম ফসল যোগ করুন',
        
        // Crops Page
        'my_crops' => 'আমার ফসল',
        'add_crop' => 'ফসল যোগ করুন',
        'crop_name' => 'ফসলের নাম',
        'variety' => 'প্রকার',
        'area_hectares' => 'এলাকা (হেক্টর)',
        'planted_date' => 'রোপণের তারিখ',
        'expected_harvest' => 'প্রত্যাশিত ফসল',
        'status' => 'অবস্থা',
        'variety_eg' => 'যেমন, ব্রি ধান ২৮',
        'rice_wheat_etc' => 'ধান, গম, ইত্যাদি',
        'no_crops_added' => 'এখনও কোন ফসল যোগ করা হয়নি',
        'add_first_crop_form' => 'শুরু করতে বাম দিকের ফর্ম ব্যবহার করে আপনার প্রথম ফসল যোগ করুন।',
        'delete' => 'মুছুন',
        'planted' => 'রোপিত',
        
        // Disease Detection
        'analyze_photo' => 'ছবি বিশ্লেষণ করুন',
        'select_crop' => 'ফসল নির্বাচন করুন',
        'choose_crop' => 'ফসল চয়ন করুন',
        'upload_image' => 'ছবি আপলোড করুন',
        'jpg_png_max' => 'JPG, PNG (সর্বোচ্চ ৫০ এমবি)',
        'analyze' => 'বিশ্লেষণ করুন',
        'how_to_use' => 'কীভাবে ব্যবহার করবেন',
        'take_clear_photo' => 'প্রভাবিত এলাকার একটি স্পষ্ট ছবি তুলুন',
        'good_lighting' => 'ভাল আলো নির্ভুলতা সাহায্য করে',
        'upload_get_results' => 'আপলোড করুন এবং ফলাফল পান',
        'add_crop_first' => 'রোগ বিশ্লেষণ করতে প্রথমে একটি ফসল যোগ করুন',
        
        // Chat Page
        'chat_with_chashi' => 'চাষির সাথে চ্যাট করুন',
        'ask_questions' => 'প্রশ্ন জিজ্ঞাসা করুন',
        'no_chat_history' => 'এখনও কোন চ্যাট ইতিহাস নেই। প্রশ্ন করা শুরু করুন!',
        'ask_about_crops' => 'ফসল, রোগ, আবহাওয়া সম্পর্কে জিজ্ঞাসা করুন...',
        'send' => 'পাঠান',
        'ask_about' => 'সম্পর্কে জিজ্ঞাসা করুন',
        'crop_management_tips' => 'ফসল পরিচালনা এবং টিপস',
        'disease_identification' => 'রোগ সনাক্তকরণ',
        'fertilizer_watering' => 'সার এবং জল',
        'weather_alerts' => 'আবহাওয়া এবং সতর্কতা',
        'farm_equipment' => 'খামার সরঞ্জাম',
        
        // Weather Page
        'weather_alerts_title' => 'আবহাওয়া এবং সতর্কতা',
        'realtime_weather_info' => 'রিয়েল-টাইম আবহাওয়া তথ্য এবং দুর্যোগ সতর্কতা',
        'current_weather' => 'বর্তমান আবহাওয়া',
        'humidity' => 'আর্দ্রতা',
        'wind_speed' => 'বাতাসের গতি',
        'rainfall' => 'বৃষ্টিপাত',
        'pressure' => 'চাপ',
        'your_region' => 'আপনার অঞ্চল',
        'auto_detect_location' => 'স্বয়ংক্রিয়-সনাক্ত অবস্থান',
        'day_forecast' => '৭-দিনের পূর্বাভাস',
        'day' => 'দিন',
        'condition' => 'অবস্থা',
        'max_temp' => 'সর্বোচ্চ তাপমাত্রা',
        'min_temp' => 'সর্বনিম্ন তাপমাত্রা',
        'today' => 'আজ',
        'tomorrow' => 'আগামীকাল',
        
        // Marketplace
        'farm_marketplace' => 'খামার বাজার',
        'buy_sell_direct' => 'কৃষকদের থেকে সরাসরি খামার পণ্য ক্রয় এবং বিক্রয় করুন',
        'add_your_product' => 'আপনার পণ্য যোগ করুন',
        'product_name' => 'পণ্যের নাম',
        'description' => 'বিবরণ',
        'price_per_unit' => 'ইউনিট প্রতি মূল্য (৳)',
        'quantity_available' => 'উপলব্ধ পরিমাণ',
        'list_product' => 'পণ্য তালিকাভুক্ত করুন',
        'search_filter' => 'অনুসন্ধান এবং ফিল্টার',
        'search_products' => 'পণ্য অনুসন্ধান করুন...',
        'filter_category' => 'বিভাগ দ্বারা ফিল্টার করুন',
        'filter_region' => 'অঞ্চল দ্বারা ফিল্টার করুন',
        'all_categories' => 'সব বিভাগ',
        'all_regions' => 'সব অঞ্চল',
        'available_products' => 'উপলব্ধ পণ্য',
        'available' => 'উপলব্ধ',
        'contact_seller' => 'বিক্রেতার সাথে যোগাযোগ করুন',
        
        // Community
        'farmer_community' => 'কৃষক সম্প্রদায় ফোরাম',
        'share_experiences' => 'অভিজ্ঞতা শেয়ার করুন, প্রশ্ন জিজ্ঞাসা করুন, এবং অন্যান্য কৃষকদের থেকে শিখুন',
        'create_new_post' => 'নতুন পোস্ট তৈরি করুন',
        'title' => 'শিরোনাম',
        'whats_on_mind' => 'আপনার মনে কী আছে?',
        'category' => 'বিভাগ',
        'content' => 'বিষয়বস্তু',
        'share_experience' => 'আপনার অভিজ্ঞতা বা প্রশ্ন শেয়ার করুন...',
        'post' => 'পোস্ট করুন',
        'community_stats' => 'সম্প্রদায় পরিসংখ্যান',
        'total_farmers' => 'মোট কৃষক',
        'posts_today' => 'আজকের পোস্ট',
        'active_discussions' => 'সক্রিয় আলোচনা',
        'popular_topics' => 'জনপ্রিয় বিষয়',
        'recent_posts' => 'সাম্প্রতিক পোস্ট',
        'likes' => 'লাইক',
        'reply' => 'উত্তর দিন',
        
        // Login Page
        'login_to_smart_chashi' => 'স্মার্ট চাষিতে লগইন করুন',
        'access_dashboard' => 'আপনার কৃষি ড্যাশবোর্ড অ্যাক্সেস করুন এবং আপনার ফসল পরিচালনা করুন',
        'email_address' => 'ইমেইল ঠিকানা',
        'password' => 'পাসওয়ার্ড',
        'no_account' => 'কোন অ্যাকাউন্ট নেই?',
        'register_here' => 'এখানে নিবন্ধন করুন',
        'new_to_smart_chashi' => 'স্মার্ট চাষিতে নতুন?',
        'join_thousands' => 'এআই-চালিত স্মার্ট কৃষি ব্যবহার করে হাজার হাজার কৃষকের সাথে যোগ দিন।',
        'key_features' => 'মূল বৈশিষ্ট্য',
        'create_account' => 'অ্যাকাউন্ট তৈরি করুন',
        
        // Register Page
        'join_smart_chashi' => 'স্মার্ট চাষিতে যোগ দিন',
        'create_farming_journey' => 'আপনার অ্যাকাউন্ট তৈরি করুন এবং আপনার স্মার্ট কৃষি যাত্রা শুরু করুন',
        'already_account' => 'ইতিমধ্যে একটি অ্যাকাউন্ট আছে?',
        'login_here' => 'এখানে লগইন করুন',
        'farmer' => 'কৃষক',
        'agriculture_officer' => 'কৃষি কর্মকর্তা',
        'agree_terms' => 'আমি পরিষেবার শর্তাবলী এবং গোপনীয়তা নীতিতে সম্মত',
        'minimum_8_chars' => 'ন্যূনতম ৮ অক্ষর',
        'reenter_password' => 'পুনরায় পাসওয়ার্ড লিখুন',
        
        // AI Agent Page
        'agent_page_title' => 'স্মার্ট চাষী - আপনার বিশেষজ্ঞ কৃষি সহায়ক',
        'agent_tagline' => 'আপনার কৃষি সংক্রান্ত প্রশ্ন করুন এবং AI থেকে নির্ভুল উত্তর পান!',
        'agent_placeholder' => 'এখানে আপনার কৃষি সংক্রান্ত প্রশ্ন করুন...',
        'voice_button' => 'ভয়েসে প্রশ্ন করুন',
        'alert_title_voice_na' => 'ভয়েস উপলব্ধ নেই',
        'voice_text_reading' => 'উত্তর পড়া হচ্ছে...',
        'detected_language' => 'সনাক্তকৃত ভাষা',
        'translated_query' => 'অনুবাদিত প্রশ্ন',
        'error_connection' => 'ত্রুটি: সার্ভারের সাথে সংযোগ করা যায়নি। অনুগ্রহ করে আপনার ইন্টারনেট সংযোগ পরীক্ষা করুন।',
        'stop_voice' => 'ভয়েস বন্ধ করুন',
    ]
];

// Get current language
function get_language() {
    if (isset($_SESSION['language'])) {
        return $_SESSION['language'];
    }
    if (isset($_COOKIE['language'])) {
        return $_COOKIE['language'];
    }
    return 'en'; // Default language
}

// Translate text
function __($key) {
    global $languages;
    $lang = get_language();
    
    if (isset($languages[$lang][$key])) {
        return $languages[$lang][$key];
    }
    return $languages['en'][$key] ?? $key;
}

// Alias for __()
function get_text($key) {
    return __($key);
}
